### ISSUE TITLE
Adding functions

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-space#1]
Hey @vigji, 

Just putting here the proposal of adding a few methods and attributes that are currently in brainrender but would probably make more sense to have here. 

- get root center and bounds (extent of root mesh within the reference space)
- get the plane (location and norm) dividing the two hemispheres
- mirror point across hemispheres
- plane norms (e.g. the norm of a sagittal plane in ARA is [0, 0, 1])

Let me know what you think about it, if and where we should have these...

**Comment by vigji** [comment]
So, I think it makes perfect sense to have here:
1) get planes/planes norms by name "sagittal", etc, either by specifying an hairline cross croordinate or selecting the mid plane. Although, considering that all atlases have standard orientation, also the stuff  in `brainatlas_api `can be handled with a dict just by knowing brainglobe standard orientation
2) mirroring of points given a plane might be handled here, although if it's a plane orthogonal to the stack is just a subtraction and I would probably keep a simple operation within `brainatlas_api`.
3) as there's nothing about meshes in this library, I would leave root center and bounds in the `brainatlas_api`

**Comment by FedeClaudi** [comment]
sounds good, we can do all of the above in brainatlas_api then

**Comment by vigji** [comment]
I would anyway adding a dict of plane normals of a space

**Comment by FedeClaudi** [comment]
I think that would be good indeed, at the moment that's how I'm doing it in BR and it works quite well.

**Comment by vigji** [comment]
@FedeClaudi what about the direction of the normal for a plane? Do you just care about non-zero axis?

**Comment by FedeClaudi** [comment]
I think specifying it as e.g. `[0, 1, 0]` would be good no ?

**Comment by vigji** [comment]
yeah it's just that it will mean two different things for two spaces with an axis which is reverted, but I guess it's no big deal

**Comment by vigji** [comment]
like, in two spaces going either anterior-posterior or posterior-anterior, the normal of the frontal section will point at opposite directions with respect to the animal

**Comment by FedeClaudi** [comment]
Yeah, that makes sense. I don't know what the best way to implement this is.. I guess it can be `[0, 1, 0]` for one and `[0, -1, 0]` for the other. But maybe there's a better way, you're the expert here!

**Comment by vigji** [comment]
Let's keep it simple and just have 1s and 0s, specifying that direction is atlas specific, I don't want to enforce explicit axes directions anywhere :)
