### ISSUE TITLE
Further clarify orientation conventions with examples

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-space#10]
The orientation strings (e.g. `psr`) are critical for using cellfinder and brainrender properly. However, some users are confused, so I'd like to add some more examples to fully clarify this.

@vigji What do you think? Maybe at https://docs.brainglobe.info/bg-space/ ?

**Comment by FedeClaudi** [comment]
I find that the use of shortened strings like `psr` while convenient reduces in clarity, I'd be in favour of forcing the extended syntax `posterior`, `superior`, `rostral`. 

Aside from that, I think the docs explain things well, perhaps was missing is some graphics illustrating the idea? I think having some schematics would really help here. I'm happy to give it a go if yous think its worth it

**Comment by adamltyson** [comment]
I'd vote for continuing to accept the shortened strings. These are used for command line input in cellfinder/brainreg, and it would be a pain for users to have to type `--orientation posterior superior left`.

>perhaps was missing is some graphics illustrating the idea? I

Yep, I think that's what's missing, maybe as part of a dedicated page (separate to the rest of bg-space) that we can point users to.
