### ISSUE TITLE
Dead Link in "Using Notebooks" docs

### ISSUE THREAD

**Issue by LSilvagnoli** [brainglobe/bg-space#11]
Hello,

Notice you have broken Link line 4  in "Using Notebooks" documentation page.

![image](https://user-images.githubusercontent.com/95351758/145840598-8f820da8-db21-4450-b49a-ca5a27e12e67.png)

**Comment by vigji** [comment]
Where exactly is the broken link? I'm not sure you're referring to this package,`bg-space`
