### ISSUE TITLE
Docstring does not correspond to usage

### ISSUE THREAD

**Issue by vilim** [brainglobe/bg-space#4]
In the docstring for a new `SpaceConvention` dorsal and ventral are mentioned, but they are not accepted when used to construct the object. Maybe aliases can be supported? (dorsal - superior, rostral - anterior)

**Comment by vigji** [comment]
Yes, will add the option! I was just worried about the confusion with the initial letters, but when used in full there should be no problems with this specification

**Comment by vigji** [comment]
The docstring is fixed, aliases will follow
