### ISSUE TITLE
Sort out confusion with cartesian/ij indexing

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-space#6]
When describing a space, confusion can arise when thinking about coordinates, as different visualisation systems (namely, cartesian-centric as scatterplots/meshes, and image-centric, as imshow and napari views) will end up having different origin convention for describing the same volume. There could be an additional argument in the init of the space describing how that origin was sorted out, and can assist with the correct flips required in the different scenarios in the rest of the BrainGlobe packages.

**Comment by vigji** [comment]
I decided not to leave so many ambiguities in defining the origin; so for the time being origin in bg-space remains based on ij indexing as all images do.

**Comment by FedeClaudi** [comment]
Still need to implement the brainrender side of things, might come around trying stuff tomorrow.
